/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_axaet_jni_activity_JniActivity */

#ifndef _Included_com_axaet_jni_activity_JniActivity
#define _Included_com_axaet_jni_activity_JniActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_axaet_jni_activity_JniActivity
 * Method:    showDialog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_axaet_jni_activity_JniActivity_showDialog
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
