/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_axaet_jni_activity_EncryptUtil */

#ifndef _Included_com_axaet_jni_activity_EncryptUtil
#define _Included_com_axaet_jni_activity_EncryptUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_axaet_jni_activity_EncryptUtil
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_axaet_jni_activity_EncryptUtil_encrypt
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_axaet_jni_activity_EncryptUtil
 * Method:    decrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_axaet_jni_activity_EncryptUtil_decrypt
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_axaet_jni_activity_EncryptUtil
 * Method:    encodeArray
 * Signature: ([I)[I
 */
JNIEXPORT void JNICALL Java_com_axaet_jni_activity_EncryptUtil_encodeArray
        (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_axaet_jni_activity_EncryptUtil
 * Method:    encodeReturnArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_axaet_jni_activity_EncryptUtil_encodeReturnArray
        (JNIEnv *, jclass, jintArray);



#ifdef __cplusplus
}
#endif
#endif
